### PR TITLE
Introduce optional smearing cutoff in lattice

### PR DESCRIPTION
**Pull request by NGoetz**
Smearing is at the moment done over the whole lattice. Optionally, we can choose now to only smear in a certain range.

### CODE REVIEW

**Review by Hendrik1704 — COMMENTED** [review]
It might be a matter of taste how to implement the limited smearing.
I usually prefer to put some $N\sigma$ (with $N$ mostly 3) limit for the Gaussian which is smeared on the grid instead of having to give a number of grid points for the smearing, because then you also have to remember the grid spacing in physical distances.

@NGoetz and @nilssass what do you think about this?

**Comment by NGoetz** [comment]
I would actually agree. That was just a quick implementation to emulate
vHLLE behaviour, but defining it in sigmas is more physical indeed.

**Comment by Hendrik1704** [comment]
Ok, then let's go with the $\sigma$ version.
When you are finished, I will use this function as a starting point for the functionality to have covariant smearing on the lattice for the conserved charges hydro input.

**Comment by NGoetz** [comment]
I have changed it accordingly.

**Review by Hendrik1704 — APPROVED** [review]
Seems fine

**Pull request merged**
